common:
  includes:
  - Drivers
  - Drivers\CMSIS
  - Drivers\CMSIS\Device
  - Drivers\CMSIS\Device\ST
  - Drivers\CMSIS\Device\ST\STM32F1xx
  - Drivers\CMSIS\Device\ST\STM32F1xx\Include
  - Drivers\CMSIS\Include
  - Drivers\STM32F1xx_HAL_Driver
  - Drivers\STM32F1xx_HAL_Driver\Inc
  - Drivers\STM32F1xx_HAL_Driver\Inc\Legacy
  - Inc
  - Middlewares
  - Middlewares\ST
  - Middlewares\ST\STM32_USB_Device_Library
  - Middlewares\ST\STM32_USB_Device_Library\Class
  - Middlewares\ST\STM32_USB_Device_Library\Class\CDC
  - Middlewares\ST\STM32_USB_Device_Library\Class\CDC\Inc
  - Middlewares\ST\STM32_USB_Device_Library\Core
  - Middlewares\ST\STM32_USB_Device_Library\Core\Inc
  - Middlewares\Third_Party
  - Middlewares\Third_Party\FatFs
  - Middlewares\Third_Party\FatFs\src
  sources:
    Drivers:
    - Drivers\STM32F1xx_HAL_Driver\Src
    Middlewares:
    - Middlewares\ST\STM32_USB_Device_Library\Class\CDC\Src
    - Middlewares\ST\STM32_USB_Device_Library\Core\Src
    - Middlewares\Third_Party\FatFs\src
    - Middlewares\Third_Party\FatFs\src\option
    Src:
    - Src
  target:
  - stm32f103rb
tool_specific:
  iar_arm:
    macros:
    - USE_HAL_DRIVER
    - STM32F103xB    
    sources:
      StartUp:
      - IDE\EWARM
    linker_file:
    - IDE\EWARM\stm32f103xb_flash.icf
